name: Run Cypress Tests Daily

on:
    schedule:
      - cron: '30 9 * * *' # เวลา 16:30 ไทย (9:30 UTC)

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # ดึงโค้ดจากโปรเจกต์
      - name: Checkout code
        uses: actions/checkout@v3

      # ติดตั้ง Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # ติดตั้ง dependencies
      - name: Install dependencies
        run: npm install

      # รัน Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} 
