name: Run Cypress Tests Daily

on:
  schedule:
    - cron: '30 6 * * *' # 13:30

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # แสดงวันที่รันใน Log
      - name: Print today's date
        run: echo "Test is running on $(date +"%d-%m-%Y")"
        
      # ดึงโค้ดจากโปรเจกต์
      - name: Checkout code
        uses: actions/checkout@v3

      # ติดตั้ง Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # ติดตั้ง dependencies
      - name: Install dependencies
        run: npm install

      # ติดตั้ง Cypress binary (ถ้าไม่มี)
      - name: Install Cypress
        run: npx cypress install

      # รัน Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
