name: Run Cypress Tests Daily

on:
  schedule:
    - cron: '0 22 * * *' # เวลา 5 โมงเช้าไทย (22:00 UTC)

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # ดึงโค้ดจากโปรเจกต์
      - name: Checkout code
        uses: actions/checkout@v3

      # ติดตั้ง Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Cache node_modules และ Cypress binary
      - name: Cache Cypress binary and node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # ติดตั้ง dependencies
      - name: Install dependencies
        run: npm install

      # ติดตั้ง Cypress binary (ถ้าไม่มี)
      - name: Install Cypress
        run: npx cypress install

      # รัน Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
